const http=require('http');
const fs=require('fs');
const path=require('path');
const WebSocket=require('ws');
const PORT=process.env.PORT||3000;
const HOST='0.0.0.0';
const DB_FILE=process.env.DOND_DB||path.join(__dirname,'dond-database.json');
let db={version:1,groups:{}};
try{if(fs.existsSync(DB_FILE))db=JSON.parse(fs.readFileSync(DB_FILE,'utf8'));}catch(e){console.error('Database reset:',e.message)}
const rooms=new Map();
const send=(ws,msg)=>{if(ws&&ws.readyState===WebSocket.OPEN)ws.send(JSON.stringify(msg));};
const clean=s=>String(s||'').trim().slice(0,80);
function save(){try{fs.writeFileSync(DB_FILE,JSON.stringify(db,null,2))}catch(e){console.error('save:',e.message)}}
function info(r){return{roomId:r.id,groupName:r.groupName,started:r.started,timer:r.timer,players:[...r.players.values()].map(p=>({id:p.id,name:p.name,status:p.status,score:p.score,opened:p.opened}))}}
function closeRoom(id,msg){const r=rooms.get(id);if(!r)return;for(const p of r.players.values())send(p.ws,{type:'error',code:'room_closed',msg:msg||'Room closed'});send(r.host,{type:'error',code:'room_closed',msg:msg||'Room closed'});rooms.delete(id)}
const server=http.createServer((req,res)=>{res.setHeader('Access-Control-Allow-Origin','*');res.setHeader('Cache-Control','no-store');const u=new URL(req.url,'http://localhost');if(u.pathname==='/health'||u.pathname==='/api/status'){res.writeHead(200,{'Content-Type':'application/json'});return res.end(JSON.stringify({status:'online',rooms:rooms.size}))}if(u.pathname==='/api/db'){res.writeHead(200,{'Content-Type':'application/json'});return res.end(JSON.stringify(db))}let file=u.pathname==='/'?path.join(__dirname,'index.html'):path.join(__dirname,path.basename(u.pathname));if(!fs.existsSync(file))file=path.join(__dirname,'DealOrNoDeal-IMPROVED.html');fs.readFile(file,(e,data)=>{if(e){res.writeHead(404);return res.end('Game file not found')}res.writeHead(200,{'Content-Type':'text/html; charset=utf-8'});res.end(data)})});
const wss=new WebSocket.Server({server});
wss.on('connection',ws=>{let roomId=null,playerId=null,host=false;const error=(code,msg)=>send(ws,{type:'error',code,msg});ws.on('message',raw=>{let m;try{m=JSON.parse(raw)}catch{return error('bad_message','Invalid message')}if(m.type==='host_create'){const id=clean(m.roomId).toUpperCase();if(!/^[A-Z0-9]{3,8}$/.test(id))return error('bad_code','Room code must be 3-8 letters/numbers');if(rooms.has(id))return error('code_in_use','Room is already in use');const group=clean(m.groupName)||'Classroom';const r={id,groupName:group,host:ws,started:false,timer:{enabled:!!m.timerEnabled,seconds:Math.max(5,Math.min(300,Number(m.timerSeconds)||30))},players:new Map()};rooms.set(id,r);roomId=id;host=true;send(ws,{type:'host_created',roomId:id,group:{name:group},info:info(r)})}
else if(m.type==='room_check'){const r=rooms.get(clean(m.roomId).toUpperCase());if(!r)return error('room_not_found','Room not found');send(ws,{type:'room_ok',roomId:r.id,groupName:r.groupName,started:r.started,timer:r.timer})}
else if(m.type==='player_join'){const r=rooms.get(clean(m.roomId).toUpperCase());if(!r)return error('room_not_found','Room not found');const name=clean(m.playerName);if(name.length<2)return error('name_short','Enter at least 2 characters');const id='p_'+Math.random().toString(36).slice(2,10);const p={id,name,ws,status:r.started?'playing':'waiting',score:0,opened:0};r.players.set(id,p);roomId=r.id;playerId=id;send(ws,{type:'player_joined',playerId:id,playerName:name,roomId:r.id,groupName:r.groupName,started:r.started,timer:r.timer});if(r.started)send(ws,{type:'host_message',payload:r.startPayload});send(r.host,{type:'room_info',info:info(r)})}
else if(m.type==='host_broadcast'){const r=rooms.get(roomId);if(!r||!host)return;if(m.payload&&m.payload.cmd==='start_game'){r.started=true;r.startPayload=m.payload;if(m.payload.timer)r.timer=m.payload.timer}for(const p of r.players.values())send(p.ws,{type:'host_message',payload:m.payload});send(ws,{type:'room_info',info:info(r)})}
else if(m.type==='player_update'){const r=rooms.get(roomId),p=r&&r.players.get(playerId);if(!p)return;Object.assign(p,{status:m.status||p.status,score:Number(m.score)||p.score,opened:Number(m.opened)||p.opened});send(r.host,{type:'room_info',info:info(r)})}
else if(m.type==='player_result'){const r=rooms.get(roomId),p=r&&r.players.get(playerId);if(!p)return;p.status='done';p.score=Number(m.ptsNum)||p.score;const g=db.groups[r.groupName]||(db.groups[r.groupName]={name:r.groupName,results:[]});g.results.push({...m,playerName:p.name,datetime:new Date().toISOString()});save();send(r.host,{type:'room_info',info:info(r)})}
else if(m.type==='host_end'){if(host)closeRoom(roomId,'The host ended the room')};});ws.on('close',()=>{const r=rooms.get(roomId);if(!r)return;if(host)return closeRoom(roomId,'The host disconnected');const p=r.players.get(playerId);if(p){p.status='disconnected';p.ws=null;send(r.host,{type:'room_info',info:info(r)})}})});
server.listen(PORT,HOST,()=>console.log(`Deal or No Deal server listening on ${PORT}`));
